# Generated by Django 4.2.1 on 2023-06-04 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_cargo_alter_libro_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=45, verbose_name='contraseña')),
                ('Cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.cargo')),
            ],
        ),
    ]
