# Generated by Django 4.2.1 on 2023-06-04 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='contraseña',
            new_name='contraseña1',
        ),
        migrations.AlterField(
            model_name='login',
            name='Cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.cargo', verbose_name='Cargo'),
        ),
    ]
