# Generated by Django 4.2.1 on 2023-06-04 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0006_rename_contraseña_login_contraseña1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='Cargo',
            new_name='tipo_cargo',
        ),
    ]
