# Generated by Django 4.2.1 on 2023-06-04 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_rename_cargo_login_tipo_cargo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='contraseña1',
            new_name='contraseña',
        ),
    ]
