# Generated by Django 4.2.2 on 2023-06-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0011_dcomision_dinformes_djustificaciones_dlicenciasrem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tdocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=100, verbose_name='tipo_documento')),
            ],
        ),
        migrations.CreateModel(
            name='unidadCIP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidad_cip', models.CharField(max_length=100, verbose_name='unidad_cip')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=45, verbose_name='Apellidos')),
                ('Correo', models.EmailField(max_length=45, verbose_name='Correo')),
                ('DNI', models.CharField(max_length=8, verbose_name='DNI')),
                ('Telefono', models.IntegerField(verbose_name='Telefono')),
                ('codigo_uca', models.IntegerField(verbose_name='Codigo_UCA')),
                ('tipo_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuarios', to='libreria.cargo', verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='personal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=45, verbose_name='Apellidos')),
                ('Correo', models.EmailField(max_length=45, verbose_name='Correo')),
                ('DNI', models.CharField(max_length=8, verbose_name='DNI')),
                ('Telefono', models.IntegerField(verbose_name='Telefono')),
                ('codigo_uca', models.IntegerField(verbose_name='Codigo_UCA')),
                ('tipo_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Personal', to='libreria.cargo', verbose_name='Cargo')),
                ('unidad_cip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidadCIP', to='libreria.unidadcip', verbose_name='unidadCIP')),
            ],
        ),
    ]
