# Generated by Django 4.2.2 on 2023-06-24 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0012_tdocumento_unidadcip_usuario_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcomision',
            name='personal_procedencia',
        ),
        migrations.RemoveField(
            model_name='dcomision',
            name='titulo',
        ),
        migrations.AddField(
            model_name='dcomision',
            name='fecha',
            field=models.DateField(default=None, verbose_name='Fecha de Recepcion'),
        ),
        migrations.AddField(
            model_name='dcomision',
            name='mes',
            field=models.CharField(default=None, max_length=25, verbose_name='Mes Correspondiente'),
        ),
        migrations.AddField(
            model_name='dcomision',
            name='personal',
            field=models.CharField(default=None, max_length=50, verbose_name='personal'),
        ),
        migrations.AddField(
            model_name='dcomision',
            name='procedencia',
            field=models.CharField(default=None, max_length=50, verbose_name='Procedencia'),
        ),
        migrations.AddField(
            model_name='dcomision',
            name='tipo_cargo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='com_usuarios', to='libreria.cargo', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='dcomision',
            name='tipo_documento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Documentos', to='libreria.tdocumento', verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='dcomision',
            name='archivo',
            field=models.FileField(default=None, upload_to='documentos/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='dcomision',
            name='descripcion',
            field=models.TextField(default=None, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='dcomision',
            name='numero',
            field=models.CharField(default=None, max_length=50, verbose_name='Numero'),
        ),
    ]
