# Generated by Django 4.2.2 on 2023-06-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0014_alter_dcomision_personal_alter_dcomision_procedencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcomision',
            name='personal',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='personal'),
        ),
        migrations.AlterField(
            model_name='dcomision',
            name='procedencia',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Procedencia'),
        ),
    ]
