# Generated by Django 4.2.2 on 2023-06-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0015_alter_dcomision_personal_alter_dcomision_procedencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rfecha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=100, verbose_name='fecha')),
            ],
        ),
        migrations.AlterField(
            model_name='dcomision',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=1, verbose_name='Mes Correspondiente'),
        ),
    ]
