# Generated by Django 4.2.2 on 2023-06-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0016_rfecha_alter_dcomision_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcomision',
            name='mes',
            field=models.CharField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=1, max_length=20, verbose_name='Mes Correspondiente'),
        ),
    ]
