# Generated by Django 4.2.2 on 2023-06-24 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0017_alter_dcomision_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcomision',
            name='registrado',
            field=models.BooleanField(default=False, verbose_name='¿Registrado?'),
        ),
        migrations.AlterField(
            model_name='dcomision',
            name='mes',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default=1, max_length=20, verbose_name='Mes Correspondiente'),
        ),
        migrations.AlterField(
            model_name='dcomision',
            name='personal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='per_comision', to='libreria.personal', verbose_name='personal'),
        ),
        migrations.AlterField(
            model_name='dcomision',
            name='procedencia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro_comision', to='libreria.unidadcip', verbose_name='procedencia'),
        ),
        migrations.AlterField(
            model_name='dcomision',
            name='tipo_cargo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com_usuarios', to='libreria.cargo', verbose_name='Cargo'),
        ),
    ]
