# Generated by Django 4.2.2 on 2023-06-25 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0020_remove_dinformes_personal_procedencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlicenciasrem',
            name='personal_procedencia',
        ),
        migrations.RemoveField(
            model_name='dlicenciasrem',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='dlicenciassinrem',
            name='personal_procedencia',
        ),
        migrations.RemoveField(
            model_name='dlicenciassinrem',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='dvacacionespend',
            name='personal_procedencia',
        ),
        migrations.RemoveField(
            model_name='dvacacionespend',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='dvacacionesprox',
            name='personal_procedencia',
        ),
        migrations.RemoveField(
            model_name='dvacacionesprox',
            name='titulo',
        ),
        migrations.AddField(
            model_name='dlicenciasrem',
            name='fecha',
            field=models.DateField(default=None, verbose_name='Fecha de Recepcion'),
        ),
        migrations.AddField(
            model_name='dlicenciasrem',
            name='mes',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default=1, max_length=20, verbose_name='Mes Correspondiente'),
        ),
        migrations.AddField(
            model_name='dlicenciasrem',
            name='personal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rem_personal', to='libreria.personal', verbose_name='personal'),
        ),
        migrations.AddField(
            model_name='dlicenciasrem',
            name='procedencia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rem_procedencia', to='libreria.unidadcip', verbose_name='procedencia'),
        ),
        migrations.AddField(
            model_name='dlicenciasrem',
            name='registrado',
            field=models.BooleanField(default=False, verbose_name='¿Registrado?'),
        ),
        migrations.AddField(
            model_name='dlicenciasrem',
            name='tipo_cargo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rem_usuarios', to='libreria.cargo', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='dlicenciasrem',
            name='tipo_documento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rem_documentos', to='libreria.tdocumento', verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='dlicenciassinrem',
            name='fecha',
            field=models.DateField(default=None, verbose_name='Fecha de Recepcion'),
        ),
        migrations.AddField(
            model_name='dlicenciassinrem',
            name='mes',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default=1, max_length=20, verbose_name='Mes Correspondiente'),
        ),
        migrations.AddField(
            model_name='dlicenciassinrem',
            name='personal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sinr_personal', to='libreria.personal', verbose_name='personal'),
        ),
        migrations.AddField(
            model_name='dlicenciassinrem',
            name='procedencia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sinr_procedencia', to='libreria.unidadcip', verbose_name='procedencia'),
        ),
        migrations.AddField(
            model_name='dlicenciassinrem',
            name='registrado',
            field=models.BooleanField(default=False, verbose_name='¿Registrado?'),
        ),
        migrations.AddField(
            model_name='dlicenciassinrem',
            name='tipo_cargo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sinr_usuarios', to='libreria.cargo', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='dlicenciassinrem',
            name='tipo_documento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sinr_documentos', to='libreria.tdocumento', verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='dvacacionespend',
            name='fecha',
            field=models.DateField(default=None, verbose_name='Fecha de Recepcion'),
        ),
        migrations.AddField(
            model_name='dvacacionespend',
            name='mes',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default=1, max_length=20, verbose_name='Mes Correspondiente'),
        ),
        migrations.AddField(
            model_name='dvacacionespend',
            name='personal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pend_personal', to='libreria.personal', verbose_name='personal'),
        ),
        migrations.AddField(
            model_name='dvacacionespend',
            name='procedencia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pend_procedencia', to='libreria.unidadcip', verbose_name='procedencia'),
        ),
        migrations.AddField(
            model_name='dvacacionespend',
            name='registrado',
            field=models.BooleanField(default=False, verbose_name='¿Registrado?'),
        ),
        migrations.AddField(
            model_name='dvacacionespend',
            name='tipo_cargo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pend_usuarios', to='libreria.cargo', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='dvacacionespend',
            name='tipo_documento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pend_documentos', to='libreria.tdocumento', verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='dvacacionesprox',
            name='fecha',
            field=models.DateField(default=None, verbose_name='Fecha de Recepcion'),
        ),
        migrations.AddField(
            model_name='dvacacionesprox',
            name='mes',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default=1, max_length=20, verbose_name='Mes Correspondiente'),
        ),
        migrations.AddField(
            model_name='dvacacionesprox',
            name='personal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prox_personal', to='libreria.personal', verbose_name='personal'),
        ),
        migrations.AddField(
            model_name='dvacacionesprox',
            name='procedencia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prox_procedencia', to='libreria.unidadcip', verbose_name='procedencia'),
        ),
        migrations.AddField(
            model_name='dvacacionesprox',
            name='registrado',
            field=models.BooleanField(default=False, verbose_name='¿Registrado?'),
        ),
        migrations.AddField(
            model_name='dvacacionesprox',
            name='tipo_cargo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prox_usuarios', to='libreria.cargo', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='dvacacionesprox',
            name='tipo_documento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prox_documentos', to='libreria.tdocumento', verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='dlicenciasrem',
            name='archivo',
            field=models.FileField(default=None, upload_to='documentos/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='dlicenciasrem',
            name='descripcion',
            field=models.TextField(default=None, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='dlicenciasrem',
            name='numero',
            field=models.CharField(default=None, max_length=50, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='dlicenciassinrem',
            name='archivo',
            field=models.FileField(default=None, upload_to='documentos/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='dlicenciassinrem',
            name='descripcion',
            field=models.TextField(default=None, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='dlicenciassinrem',
            name='numero',
            field=models.CharField(default=None, max_length=50, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='dvacacionespend',
            name='archivo',
            field=models.FileField(default=None, upload_to='documentos/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='dvacacionespend',
            name='descripcion',
            field=models.TextField(default=None, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='dvacacionespend',
            name='numero',
            field=models.CharField(default=None, max_length=50, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='dvacacionesprox',
            name='archivo',
            field=models.FileField(default=None, upload_to='documentos/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='dvacacionesprox',
            name='descripcion',
            field=models.TextField(default=None, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='dvacacionesprox',
            name='numero',
            field=models.CharField(default=None, max_length=50, verbose_name='Numero'),
        ),
    ]
